[package]
name = "boj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkill_lib = "0.1.4"
sysinfo = "0.29.10"

